import Foundation

extension GUIValidationFixtures {
    public static func ratesEngineSnapshot(projectRoot: URL) -> RatesEngineSnapshot {
        let now = Date()
        return RatesEngineSnapshot(
            generatedAt: now,
            sourceStatuses: [
                RatesEngineSourceStatus(id: "manual_inputs", ok: true, stale: false, enabled: true, required: false, lastUpdateAt: now.addingTimeInterval(-1800), mode: "manual_market_input", coverageRatio: 0.3, updatedCurrencies: 3),
                RatesEngineSourceStatus(id: "proxy_engine", ok: true, stale: false, enabled: true, required: false, lastUpdateAt: now.addingTimeInterval(-120), mode: "newspulse_policy_proxy", coverageRatio: nil, updatedCurrencies: nil),
                RatesEngineSourceStatus(id: "newspulse", ok: true, stale: false, enabled: true, required: false, lastUpdateAt: now.addingTimeInterval(-120), mode: "shared_context", coverageRatio: nil, updatedCurrencies: nil),
            ],
            currencies: [
                RatesEngineCurrencyState(
                    currency: "USD",
                    frontEndLevel: 0.84,
                    frontEndBasis: "policy_proxy_index",
                    frontEndChange1d: 0.16,
                    frontEndChange5d: 0.42,
                    expectedPathLevel: 1.08,
                    expectedPathBasis: "policy_proxy_index",
                    expectedPathChange1d: 0.24,
                    expectedPathChange5d: 0.56,
                    curveSlope2s10s: nil,
                    curveBasis: "unavailable",
                    curveShapeRegime: "UNAVAILABLE",
                    policyRepricingScore: 0.81,
                    policySurpriseScore: 0.62,
                    policyUncertaintyScore: 0.44,
                    policyDirectionScore: 0.55,
                    policyRelevanceScore: 0.78,
                    preCBEventWindow: false,
                    postCBEventWindow: true,
                    preMacroPolicyWindow: false,
                    postMacroPolicyWindow: true,
                    meetingPathRepriceNow: true,
                    macroToRatesTransmissionScore: 0.69,
                    stale: false,
                    reasons: ["USD central-bank repricing window active"]
                ),
                RatesEngineCurrencyState(
                    currency: "EUR",
                    frontEndLevel: 0.22,
                    frontEndBasis: "manual_market_input",
                    frontEndChange1d: -0.08,
                    frontEndChange5d: -0.14,
                    expectedPathLevel: 0.18,
                    expectedPathBasis: "manual_market_input",
                    expectedPathChange1d: -0.05,
                    expectedPathChange5d: -0.12,
                    curveSlope2s10s: -0.34,
                    curveBasis: "manual_market_input",
                    curveShapeRegime: "INVERSION_LIKE",
                    policyRepricingScore: 0.36,
                    policySurpriseScore: 0.18,
                    policyUncertaintyScore: 0.24,
                    policyDirectionScore: -0.14,
                    policyRelevanceScore: 0.33,
                    preCBEventWindow: false,
                    postCBEventWindow: false,
                    preMacroPolicyWindow: false,
                    postMacroPolicyWindow: false,
                    meetingPathRepriceNow: false,
                    macroToRatesTransmissionScore: 0.22,
                    stale: false,
                    reasons: ["EUR manual front-end and curve inputs available"]
                ),
            ],
            pairs: [
                RatesEnginePairState(
                    pair: "EURUSD",
                    baseCurrency: "EUR",
                    quoteCurrency: "USD",
                    frontEndDiff: -0.62,
                    expectedPathDiff: -0.90,
                    curveDivergenceScore: 0.21,
                    policyDivergenceScore: 0.74,
                    ratesRegime: "UNSTABLE",
                    ratesRiskScore: 0.79,
                    tradeGate: "BLOCK",
                    policyAlignment: "quote_hawkish",
                    meetingPathRepriceNow: true,
                    macroToRatesTransmissionScore: 0.69,
                    stale: false,
                    brokerSymbols: ["EURUSD"],
                    reasons: ["meeting path repricing active", "policy divergence meaningful"]
                ),
                RatesEnginePairState(
                    pair: "USDJPY",
                    baseCurrency: "USD",
                    quoteCurrency: "JPY",
                    frontEndDiff: 0.48,
                    expectedPathDiff: 0.54,
                    curveDivergenceScore: 0.11,
                    policyDivergenceScore: 0.58,
                    ratesRegime: "SUPPORTIVE",
                    ratesRiskScore: 0.38,
                    tradeGate: "ALLOW",
                    policyAlignment: "base_hawkish",
                    meetingPathRepriceNow: false,
                    macroToRatesTransmissionScore: 0.47,
                    stale: false,
                    brokerSymbols: ["USDJPY"],
                    reasons: ["policy divergence meaningful"]
                ),
            ],
            recentPolicyEvents: [
                RatesEnginePolicyEvent(
                    id: "evt-usd-fed",
                    currency: "USD",
                    source: "official",
                    domain: "federalreserve.gov",
                    publishedAt: now.addingTimeInterval(-600),
                    title: "Federal Reserve policy statement",
                    url: URL(string: "https://example.test/fed"),
                    policyRelevanceScore: 0.91,
                    direction: 0.56,
                    centralBankEvent: true,
                    macroPolicyEvent: false
                ),
                RatesEnginePolicyEvent(
                    id: "evt-eur-cpi",
                    currency: "EUR",
                    source: "calendar",
                    domain: "mt5-calendar",
                    publishedAt: now.addingTimeInterval(-1800),
                    title: "Euro Area CPI",
                    url: nil,
                    policyRelevanceScore: 0.62,
                    direction: -0.18,
                    centralBankEvent: false,
                    macroPolicyEvent: true
                ),
            ],
            healthSummary: [
                KeyValueRecord(key: "pair_count", value: "2"),
                KeyValueRecord(key: "currency_count", value: "2"),
            ],
            artifactPaths: [
                KeyValueRecord(key: "snapshot_json", value: projectRoot.appendingPathComponent("FXDataEngine/Tools/OfflineLab/RatesEngine/rates_engine_status.json").path),
            ]
        )
    }

    public static func microstructureSnapshot(projectRoot: URL) -> MicrostructureSnapshot {
        let now = Date()
        return MicrostructureSnapshot(
            generatedAt: now,
            serviceStatus: MicrostructureServiceStatus(
                ok: true,
                stale: false,
                enabled: true,
                pollIntervalMS: 5000,
                symbolRefreshSec: 300,
                snapshotStaleAfterSec: 45,
                lastPollAt: now.addingTimeInterval(-5),
                lastSuccessAt: now.addingTimeInterval(-5),
                lastSymbolRefreshAt: now.addingTimeInterval(-120),
                lastError: nil
            ),
            symbols: [
                MicrostructureSymbolState(
                    symbol: "EURUSD",
                    brokerSymbol: "EURUSD",
                    available: true,
                    stale: false,
                    generatedAt: now,
                    priceCostCurrent: 0.8,
                    silentGapSecondsCurrent: 0.3,
                    sessionTag: "LONDON_NEWYORK_OVERLAP",
                    handoffFlag: false,
                    minutesSinceSessionOpen: 74,
                    minutesToSessionClose: 166,
                    sessionOpenBurstScore: 0.24,
                    sessionPriceCostBehaviorScore: 0.18,
                    liquidityStressScore: 0.32,
                    hostileExecutionScore: 0.28,
                    microstructureRegime: "TRENDING_CLEAN",
                    tradeGate: "ALLOW",
                    tickImbalance30s: 0.34,
                    directionalEfficiency60s: 0.72,
                    priceCostZScore60s: 0.44,
                    tickRate60s: 126,
                    tickRateZScore60s: 1.18,
                    realizedVol5m: 0.61,
                    volBurstScore5m: 1.12,
                    localExtremaBreachScore60s: 0.21,
                    sweepAndRejectFlag60s: false,
                    breakoutReversalScore60s: 0.18,
                    exhaustionProxy60s: 0.22,
                    reasons: ["Tick imbalance supports a clean short-horizon trend"]
                ),
                MicrostructureSymbolState(
                    symbol: "GBPJPY",
                    brokerSymbol: "GBPJPY",
                    available: true,
                    stale: false,
                    generatedAt: now,
                    priceCostCurrent: 2.6,
                    silentGapSecondsCurrent: 1.6,
                    sessionTag: "LONDON_NEWYORK_OVERLAP",
                    handoffFlag: true,
                    minutesSinceSessionOpen: 12,
                    minutesToSessionClose: 18,
                    sessionOpenBurstScore: 0.74,
                    sessionPriceCostBehaviorScore: 0.66,
                    liquidityStressScore: 0.79,
                    hostileExecutionScore: 0.72,
                    microstructureRegime: "STOP_RUN_RISK",
                    tradeGate: "CAUTION",
                    tickImbalance30s: -0.11,
                    directionalEfficiency60s: 0.37,
                    priceCostZScore60s: 2.24,
                    tickRate60s: 188,
                    tickRateZScore60s: 2.11,
                    realizedVol5m: 1.42,
                    volBurstScore5m: 1.91,
                    localExtremaBreachScore60s: 0.76,
                    sweepAndRejectFlag60s: true,
                    breakoutReversalScore60s: 0.81,
                    exhaustionProxy60s: 0.73,
                    reasons: ["Recent breakout rejection detected", "Price-cost instability elevated"]
                ),
            ],
            healthSummary: [
                KeyValueRecord(key: "active_symbol_count", value: "2"),
                KeyValueRecord(key: "snapshot_stale_after_sec", value: "45"),
            ],
            artifactPaths: [
                KeyValueRecord(key: "snapshot_json", value: projectRoot.appendingPathComponent("FILE_COMMON/FXAI/Runtime/microstructure_snapshot.json").path),
                KeyValueRecord(key: "history_ndjson", value: projectRoot.appendingPathComponent("FILE_COMMON/FXAI/Runtime/microstructure_history.ndjson").path),
            ]
        )
    }
}
