#include "Trade\\runtime_trade_exposure.mqh"
#include "Trade\\runtime_trade_newspulse.mqh"
#include "Trade\\runtime_trade_risk.mqh"
#include "Trade\\runtime_trade_execution.mqh"
#include "Trade\\runtime_trade_lifecycle.mqh"
